"""Issue orchestration flow for GitHub <-> Cursor bridge."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Iterable

from agent.context_builder import build_issue_prompt, read_context_files
from agent.cursor_interface import CursorInterface

if TYPE_CHECKING:
    from agent.github_client import GitHubClient


class IssueManager:
    """Coordinates issue fetching, prompting, and optional GitHub actions."""

    def __init__(
        self,
        github_client: "GitHubClient",
        cursor_interface: CursorInterface,
        repo_name: str,
        memory_file: str = "agent/memory.json",
    ):
        self.github_client = github_client
        self.cursor_interface = cursor_interface
        self.repo_name = repo_name
        self.memory_path = Path(memory_file)

    def list_open_issues(self) -> list[str]:
        """Return a compact display list of open issues."""
        issues = self.github_client.list_open_issues()
        return [f"#{issue.number} - {issue.title}" for issue in issues]

    def resolve_issue(
        self,
        issue_number: int,
        context_files: Iterable[str] | None = None,
        post_comment: bool = False,
        add_label: str | None = None,
        close_issue: bool = False,
    ) -> str:
        """Run the issue resolution flow and optionally update GitHub."""
        issue = self.github_client.get_issue(issue_number)
        context_text = read_context_files(context_files or [])
        prompt = build_issue_prompt(
            issue_title=issue.title,
            issue_body=issue.body or "",
            repo_name=self.repo_name,
            extra_context=context_text,
        )

        ai_response = self.cursor_interface.get_response(prompt)

        if post_comment:
            comment_body = (
                "AI-assisted proposed resolution plan:\n\n"
                f"{ai_response}\n\n"
                "_Generated by local EPC17 issue agent._"
            )
            self.github_client.create_comment(issue_number, comment_body)

        if add_label:
            self.github_client.add_label(issue_number, add_label)

        if close_issue:
            self.github_client.close_issue(issue_number)

        self._log_action(
            {
                "timestamp_utc": datetime.now(timezone.utc).isoformat(),
                "issue_number": issue_number,
                "issue_title": issue.title,
                "post_comment": post_comment,
                "add_label": add_label,
                "close_issue": close_issue,
                "context_files": list(context_files or []),
            }
        )
        return ai_response

    def _log_action(self, entry: dict) -> None:
        """Append an action entry to the local memory log."""
        self.memory_path.parent.mkdir(parents=True, exist_ok=True)
        if not self.memory_path.exists():
            self.memory_path.write_text("[]", encoding="utf-8")

        try:
            data = json.loads(self.memory_path.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                data = []
        except (json.JSONDecodeError, OSError):
            data = []

        data.append(entry)
        self.memory_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

